version: '3.8'
services:
  pianno-app:
    container_name: pianno-app
    build:
      context: .
      dockerfile: ./apps/pianno/Dockerfile
    ports:
      - '3000:3000'
    image: pianno:local
  docs:
    container_name: pianno-docs
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    ports:
      - '4321:3000'
    image: pianno-docs:local