version: '3.8'
services:
  pianno-app:
    container_name: pianno-app
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - '3000:3000'
    image: pianno