# build and publish docker image to ghcr
name: pianno
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_NAME: ${{ github.repository }}
      HOSTNAME: localhost
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t $REGISTRY/$IMAGE_NAME:$TAG .

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push $REGISTRY/$IMAGE_NAME:$TAG
